
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.bootstrap-servers=10.171.133.25:9092,10.171.155.66:9092,10.171.132.219:9092
spring.kafka.consumer.group-id=yzq-test-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
