// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test-any.proto

package com.sankuai.uav.uairport.base;

public interface DummyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uav.uairport.base.DummyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any context = 1;</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.google.protobuf.Any context = 1;</code>
   * @return The context.
   */
  com.google.protobuf.Any getContext();
  /**
   * <code>.google.protobuf.Any context = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getContextOrBuilder();
}
