// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test-any.proto

package com.sankuai.uav.uairport.base;

public interface SomeContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uav.uairport.base.SomeContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
