// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test-any.proto

package com.sankuai.uav.uairport.base;

public final class UAirportBaseProto {
  private UAirportBaseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uav_uairport_base_DummyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uav_uairport_base_DummyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uav_uairport_base_SomeContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uav_uairport_base_SomeContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016test-any.proto\022\021uav.uairport.base\032\031goo" +
      "gle/protobuf/any.proto\"5\n\014DummyMessage\022%" +
      "\n\007context\030\001 \001(\0132\024.google.protobuf.Any\")\n" +
      "\013SomeContext\022\014\n\004code\030\001 \001(\005\022\014\n\004data\030\002 \001(\t" +
      "B4\n\035com.sankuai.uav.uairport.baseB\021UAirp" +
      "ortBaseProtoP\001P\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_uav_uairport_base_DummyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uav_uairport_base_DummyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uav_uairport_base_DummyMessage_descriptor,
        new java.lang.String[] { "Context", });
    internal_static_uav_uairport_base_SomeContext_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_uav_uairport_base_SomeContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uav_uairport_base_SomeContext_descriptor,
        new java.lang.String[] { "Code", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
