spring.application.name=learn-time-range-crud
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/uav-airport?useSSL=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=uav-airport
spring.datasource.password=cradle